language: node_js
node_js:
  - "10"

script: npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 987e286c243514e0a536e4724725f8ede7c21c5e
  keep-history: true
  on:
    branch: gh-pages