language: node_js
node_js:
  - "10"

script: npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 1590355559cd5d55b66276fac854d77c7802612d
  keep-history: true
  on:
    branch: master